### ISSUE TITLE
Add Mapping from ICD10 to Blocks

### ISSUE THREAD

**Issue by noxthot** [snovaisg/ICDMappings#13]
Also allow mapping from Code to Block.

E.g. A77.1 can now be mapped to **A75-A79** (Rickettsioses).

**Comment by noxthot** [comment]
@snovaisg thanks for the nice package. Would be great if you could review the change (https://github.com/snovaisg/ICD-Mappings/pull/14) and merge if you are happy with the pull request.

Can I also ask for a release with this change? Thanks a bunch. :)

**Comment by snovaisg** [comment]
Hi @noxthot! Amazing contribution, I took a look at the code and looks rly nice. I would just suggest before merging adding a few test cases for this new functionality (like we have for the other mappers) and see if they pass with pytest :)

**Comment by snovaisg** [comment]
Oh and also would be nice to update the readme file with both the source you used for the mapping, and the .show_mappers() output to now display "blocks" for icd10

**Comment by noxthot** [comment]
Thanks for your fast reply. I just updated the pull request accordingly.

**Comment by snovaisg** [comment]
Awesome! Do you have a link where you got the mappings from icd10 to the respective blocks? I like to provide the source of each mapping in the readme so people who use this tool can more easily verify and trust

**Comment by noxthot** [comment]
I used the same as you as indicated in https://github.com/noxthot/ICD-Mappings/blob/main/icdmappings/mappers/icd10_to_blocks.py#L12
